//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClimaAV.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        public System.Guid Id { get; set; }
        public long IdUsuario { get; set; }
        public int IdCiudad { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
